# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/vtrej003/assignment-andres_vincent_cs_100_assignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/vtrej003/assignment-andres_vincent_cs_100_assignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/vtrej003/assignment-andres_vincent_cs_100_assignment/CMakeFiles /home/csmajs/vtrej003/assignment-andres_vincent_cs_100_assignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/vtrej003/assignment-andres_vincent_cs_100_assignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rshell

# Build rule for target.
rshell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rshell
.PHONY : rshell

# fast build rule for target.
rshell/fast:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/build
.PHONY : rshell/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/and.o: src/and.cpp.o

.PHONY : src/and.o

# target to build an object file
src/and.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/and.cpp.o
.PHONY : src/and.cpp.o

src/and.i: src/and.cpp.i

.PHONY : src/and.i

# target to preprocess a source file
src/and.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/and.cpp.i
.PHONY : src/and.cpp.i

src/and.s: src/and.cpp.s

.PHONY : src/and.s

# target to generate assembly for a file
src/and.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/and.cpp.s
.PHONY : src/and.cpp.s

src/command.o: src/command.cpp.o

.PHONY : src/command.o

# target to build an object file
src/command.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/command.cpp.o
.PHONY : src/command.cpp.o

src/command.i: src/command.cpp.i

.PHONY : src/command.i

# target to preprocess a source file
src/command.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/command.cpp.i
.PHONY : src/command.cpp.i

src/command.s: src/command.cpp.s

.PHONY : src/command.s

# target to generate assembly for a file
src/command.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/command.cpp.s
.PHONY : src/command.cpp.s

src/executable.o: src/executable.cpp.o

.PHONY : src/executable.o

# target to build an object file
src/executable.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/executable.cpp.o
.PHONY : src/executable.cpp.o

src/executable.i: src/executable.cpp.i

.PHONY : src/executable.i

# target to preprocess a source file
src/executable.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/executable.cpp.i
.PHONY : src/executable.cpp.i

src/executable.s: src/executable.cpp.s

.PHONY : src/executable.s

# target to generate assembly for a file
src/executable.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/executable.cpp.s
.PHONY : src/executable.cpp.s

src/inputRedirect.o: src/inputRedirect.cpp.o

.PHONY : src/inputRedirect.o

# target to build an object file
src/inputRedirect.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/inputRedirect.cpp.o
.PHONY : src/inputRedirect.cpp.o

src/inputRedirect.i: src/inputRedirect.cpp.i

.PHONY : src/inputRedirect.i

# target to preprocess a source file
src/inputRedirect.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/inputRedirect.cpp.i
.PHONY : src/inputRedirect.cpp.i

src/inputRedirect.s: src/inputRedirect.cpp.s

.PHONY : src/inputRedirect.s

# target to generate assembly for a file
src/inputRedirect.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/inputRedirect.cpp.s
.PHONY : src/inputRedirect.cpp.s

src/ioRedirect.o: src/ioRedirect.cpp.o

.PHONY : src/ioRedirect.o

# target to build an object file
src/ioRedirect.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/ioRedirect.cpp.o
.PHONY : src/ioRedirect.cpp.o

src/ioRedirect.i: src/ioRedirect.cpp.i

.PHONY : src/ioRedirect.i

# target to preprocess a source file
src/ioRedirect.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/ioRedirect.cpp.i
.PHONY : src/ioRedirect.cpp.i

src/ioRedirect.s: src/ioRedirect.cpp.s

.PHONY : src/ioRedirect.s

# target to generate assembly for a file
src/ioRedirect.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/ioRedirect.cpp.s
.PHONY : src/ioRedirect.cpp.s

src/or.o: src/or.cpp.o

.PHONY : src/or.o

# target to build an object file
src/or.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/or.cpp.o
.PHONY : src/or.cpp.o

src/or.i: src/or.cpp.i

.PHONY : src/or.i

# target to preprocess a source file
src/or.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/or.cpp.i
.PHONY : src/or.cpp.i

src/or.s: src/or.cpp.s

.PHONY : src/or.s

# target to generate assembly for a file
src/or.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/or.cpp.s
.PHONY : src/or.cpp.s

src/outputAppendRedirect.o: src/outputAppendRedirect.cpp.o

.PHONY : src/outputAppendRedirect.o

# target to build an object file
src/outputAppendRedirect.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/outputAppendRedirect.cpp.o
.PHONY : src/outputAppendRedirect.cpp.o

src/outputAppendRedirect.i: src/outputAppendRedirect.cpp.i

.PHONY : src/outputAppendRedirect.i

# target to preprocess a source file
src/outputAppendRedirect.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/outputAppendRedirect.cpp.i
.PHONY : src/outputAppendRedirect.cpp.i

src/outputAppendRedirect.s: src/outputAppendRedirect.cpp.s

.PHONY : src/outputAppendRedirect.s

# target to generate assembly for a file
src/outputAppendRedirect.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/outputAppendRedirect.cpp.s
.PHONY : src/outputAppendRedirect.cpp.s

src/outputRedirect.o: src/outputRedirect.cpp.o

.PHONY : src/outputRedirect.o

# target to build an object file
src/outputRedirect.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/outputRedirect.cpp.o
.PHONY : src/outputRedirect.cpp.o

src/outputRedirect.i: src/outputRedirect.cpp.i

.PHONY : src/outputRedirect.i

# target to preprocess a source file
src/outputRedirect.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/outputRedirect.cpp.i
.PHONY : src/outputRedirect.cpp.i

src/outputRedirect.s: src/outputRedirect.cpp.s

.PHONY : src/outputRedirect.s

# target to generate assembly for a file
src/outputRedirect.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/outputRedirect.cpp.s
.PHONY : src/outputRedirect.cpp.s

src/pipe.o: src/pipe.cpp.o

.PHONY : src/pipe.o

# target to build an object file
src/pipe.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/pipe.cpp.o
.PHONY : src/pipe.cpp.o

src/pipe.i: src/pipe.cpp.i

.PHONY : src/pipe.i

# target to preprocess a source file
src/pipe.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/pipe.cpp.i
.PHONY : src/pipe.cpp.i

src/pipe.s: src/pipe.cpp.s

.PHONY : src/pipe.s

# target to generate assembly for a file
src/pipe.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/pipe.cpp.s
.PHONY : src/pipe.cpp.s

src/query.o: src/query.cpp.o

.PHONY : src/query.o

# target to build an object file
src/query.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/query.cpp.o
.PHONY : src/query.cpp.o

src/query.i: src/query.cpp.i

.PHONY : src/query.i

# target to preprocess a source file
src/query.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/query.cpp.i
.PHONY : src/query.cpp.i

src/query.s: src/query.cpp.s

.PHONY : src/query.s

# target to generate assembly for a file
src/query.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/query.cpp.s
.PHONY : src/query.cpp.s

src/rshell.o: src/rshell.cpp.o

.PHONY : src/rshell.o

# target to build an object file
src/rshell.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/rshell.cpp.o
.PHONY : src/rshell.cpp.o

src/rshell.i: src/rshell.cpp.i

.PHONY : src/rshell.i

# target to preprocess a source file
src/rshell.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/rshell.cpp.i
.PHONY : src/rshell.cpp.i

src/rshell.s: src/rshell.cpp.s

.PHONY : src/rshell.s

# target to generate assembly for a file
src/rshell.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/rshell.cpp.s
.PHONY : src/rshell.cpp.s

src/semicolon.o: src/semicolon.cpp.o

.PHONY : src/semicolon.o

# target to build an object file
src/semicolon.cpp.o:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/semicolon.cpp.o
.PHONY : src/semicolon.cpp.o

src/semicolon.i: src/semicolon.cpp.i

.PHONY : src/semicolon.i

# target to preprocess a source file
src/semicolon.cpp.i:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/semicolon.cpp.i
.PHONY : src/semicolon.cpp.i

src/semicolon.s: src/semicolon.cpp.s

.PHONY : src/semicolon.s

# target to generate assembly for a file
src/semicolon.cpp.s:
	$(MAKE) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/semicolon.cpp.s
.PHONY : src/semicolon.cpp.s

unit_tests/unit_test.o: unit_tests/unit_test.cpp.o

.PHONY : unit_tests/unit_test.o

# target to build an object file
unit_tests/unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/unit_tests/unit_test.cpp.o
.PHONY : unit_tests/unit_test.cpp.o

unit_tests/unit_test.i: unit_tests/unit_test.cpp.i

.PHONY : unit_tests/unit_test.i

# target to preprocess a source file
unit_tests/unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/unit_tests/unit_test.cpp.i
.PHONY : unit_tests/unit_test.cpp.i

unit_tests/unit_test.s: unit_tests/unit_test.cpp.s

.PHONY : unit_tests/unit_test.s

# target to generate assembly for a file
unit_tests/unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/unit_tests/unit_test.cpp.s
.PHONY : unit_tests/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rshell"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... unit_test"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/and.o"
	@echo "... src/and.i"
	@echo "... src/and.s"
	@echo "... src/command.o"
	@echo "... src/command.i"
	@echo "... src/command.s"
	@echo "... src/executable.o"
	@echo "... src/executable.i"
	@echo "... src/executable.s"
	@echo "... src/inputRedirect.o"
	@echo "... src/inputRedirect.i"
	@echo "... src/inputRedirect.s"
	@echo "... src/ioRedirect.o"
	@echo "... src/ioRedirect.i"
	@echo "... src/ioRedirect.s"
	@echo "... src/or.o"
	@echo "... src/or.i"
	@echo "... src/or.s"
	@echo "... src/outputAppendRedirect.o"
	@echo "... src/outputAppendRedirect.i"
	@echo "... src/outputAppendRedirect.s"
	@echo "... src/outputRedirect.o"
	@echo "... src/outputRedirect.i"
	@echo "... src/outputRedirect.s"
	@echo "... src/pipe.o"
	@echo "... src/pipe.i"
	@echo "... src/pipe.s"
	@echo "... src/query.o"
	@echo "... src/query.i"
	@echo "... src/query.s"
	@echo "... src/rshell.o"
	@echo "... src/rshell.i"
	@echo "... src/rshell.s"
	@echo "... src/semicolon.o"
	@echo "... src/semicolon.i"
	@echo "... src/semicolon.s"
	@echo "... unit_tests/unit_test.o"
	@echo "... unit_tests/unit_test.i"
	@echo "... unit_tests/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

